### ISSUE TITLE
About link doesn't do anything

### ISSUE THREAD

**Issue by abartov** [starakaj/wikisonnet#1]

**Comment by ricordisamoa** [comment]
Relevant to https://github.com/awanderingorill/wikisonnets_frontend instead?

**Comment by catarak** [comment]
you are definitely correct that it does nothing. we haven't officially launched wikisonnet yet so the site and api are still in flux. if you would like to know when it is launched, it is probably best to follow me on twitter at @hellothisiscass. but yes, @ricordisamoa is right, if you find bugs in the front end please post them to the front end website repository.

**Comment by abartov** [comment]
Ah, thank you!

I did not realize it was not launched yet.  I seem to have given it a bit of international publicity, and thought it a shame people who don't see my original message would not find out who made this.

Okay, all in good time! :)
